"""
DAG — Rapport quotidien fraude (Version Démo Intégrée)
Schedule : 8h00 chaque matin
"""
from datetime import datetime, timedelta
import random
import os

from airflow import DAG
from airflow.operators.python import PythonOperator

# Configuration globale pour la démo
default_args = {
    "owner": "data_team",
    "retries": 1,
    "retry_delay": timedelta(minutes=5),
    "email_on_failure": False,
    "email_on_retry": False,
}

def extract_yesterday(**context):
    """Simule l'extraction consolidée des données de la veille."""
    # En démo, on simule la date d'hier
    yesterday = (datetime.utcnow() - timedelta(days=1)).date()
    
    # Simulation réaliste des volumes
    total_tx = random.randint(12000, 18500) # Volume quotidien
    # Taux de fraude réaliste d'environ 0.1% à 0.5%
    fraud_rate_pct = random.uniform(0.1, 0.5) 
    nb_fraudes = int(total_tx * (fraud_rate_pct / 100))
    
    amount_total = round(total_tx * random.uniform(25, 75), 2)
    amount_fraud = round(nb_fraudes * random.uniform(180, 600), 2)

    data = {
        "date_reporting": str(yesterday),
        "total_transactions": total_tx,
        "total_frauds": nb_fraudes,
        "fraud_rate_pct": round(fraud_rate_pct, 3),
        "total_amount_eur": amount_total,
        "fraud_amount_eur": amount_fraud,
    }
    
    print(f"[EXTRACT] ✅ Consolidated data for {yesterday}: {total_tx} transactions analyzed.")
    print(f"[EXTRACT] {nb_fraudes} fraudulent activities confirmed.")
    context["ti"].xcom_push(key="daily_consolidated_stats", value=data)


def compute_kpis(**context):
    """Consolide les KPIs pour le rapport."""
    stats = context["ti"].xcom_pull(key="daily_consolidated_stats", task_ids="extract_yesterday")
    
    # Calculs additionnels simulés
    avg_tx_value = stats['total_amount_eur'] / stats['total_transactions']
    avg_fraud_value = stats['fraud_amount_eur'] / stats['total_frauds'] if stats['total_frauds'] > 0 else 0
    
    kpis = {
        **stats,
        "average_transaction_value": round(avg_tx_value, 2),
        "average_fraud_value": round(avg_fraud_value, 2),
    }
    
    print(f"[COMPUTE] ✅ Daily KPIs finalized for Business Review.")
    context["ti"].xcom_push(key="kpis", value=kpis)


def generate_report(**context):
    """Génère le rapport formaté."""
    kpis = context["ti"].xcom_pull(key="kpis", task_ids="compute_kpis")
    
    report_content = f"""
========================================================================
DAILY FRAUD DETECTION REPORT — {kpis['date_reporting']}
========================================================================
GLOBAL TRANSACTIONAL SUMMARY:
------------------------------------------------------------------------
Total Volume Analyzed   : {kpis['total_transactions']:,}
Total Amount Processed  : {kpis['total_amount_eur']:,} EUR
Average Ticket Value    : {kpis['average_transaction_value']} EUR
------------------------------------------------------------------------
FRAUD RISK PERFORMANCE:
------------------------------------------------------------------------
Confirmed Frauds        : {kpis['total_frauds']}
Detection Rate          : {kpis['fraud_rate_pct']}%
Total Fraudulent Amount : {kpis['fraud_amount_eur']:,} EUR
Average Fraud Value     : {kpis['average_fraud_value']} EUR
========================================================================
Generated by Apache Airflow (Jedha Lead Program)
========================================================================
"""
    print(f"[GENERATE] ✅ Formal report generated:")
    print(report_content)
    context["ti"].xcom_push(key="final_report", value=report_content)


def send_daily_email(**context):
    """Simule l'envoi du rapport par email."""
    kpis = context["ti"].xcom_pull(key="kpis", task_ids="compute_kpis")
    report = context["ti"].xcom_pull(key="final_report", task_ids="generate_report")
    
    recipient = "business-intelligence@company.com"
    subject = f"🚨 Daily Fraud Report: {kpis['date_reporting']} — {kpis['total_frauds']} Frauds Confirmed"
    
    print(f"[EMAIL] ✅ Preparing communication for {recipient}.")
    print(f"[EMAIL] Subject: {subject}")
    print(f"[EMAIL] Content simulation:\n{report}")
    print("[EMAIL] Status: Sent Successfully.")


with DAG(
    dag_id="fraud_daily_reporting_batch",
    description="Rapport quotidien consolidé des fraudes (TP Lead)",
    schedule_interval="0 8 * * *",  # Tous les jours à 8h00
    start_date=datetime(2024, 1, 1),
    catchup=False,
    default_args=default_args,
    tags=["reporting", "batch", "daily"],
) as dag:

    # Définition des tâches
    extract_task = PythonOperator(task_id="extract_yesterday", python_callable=extract_yesterday)
    compute_task = PythonOperator(task_id="compute_kpis",      python_callable=compute_kpis)
    generate_task = PythonOperator(task_id="generate_report", python_callable=generate_report)
    send_task = PythonOperator(task_id="send_daily_email",    python_callable=send_daily_email)

    # Définition des dépendances
    extract_task >> compute_task >> generate_task >> send_task